require "./registry"

module Vow
  # The marker every mountable service shares. You don't include this directly:
  # `include Vow::Exportable` (annotate the methods you want) or
  # `include Vow::Exportable::All` (export every public method) both make a
  # class a `Mountable`. `Vow::Registry#mount` / `Registry.new` restrict on this
  # type, so either flavor mounts the same way, and `Vow::Registry` can stay
  # ignorant of *how* a service decided what to export.
  #
  # The concrete `vow_install` is generated by `Vow::Exportable::Generated`
  # (the shared macro engine both mixins route through); this just names the
  # contract the registry depends on.
  module Mountable
    abstract def vow_install(registry : ::Vow::Registry) : Nil
  end
end
