require "../manifest"
require "./tree"

module Vow
  module Codegen
    # Emits the JavaScript *runtime* for a client: the `VowError` class, a
    # `createClient(transport)` ES-module function, and the batteries-included
    # `createHttpClient(url, options?)` default — all with no type annotations,
    # so a browser can import and run them with no build step. Types live in the
    # companion `.d.ts` (`TypeScript.emit_dts`) sitting next to it, which an
    # editor picks up automatically — so the buildless consumer still gets full
    # autocomplete.
    #
    # The function names, namespace nesting, and dispatch ids are byte-identical
    # to the `.d.ts` (both derive from the same manifest), so the declaration
    # describes this runtime exactly.
    module JavaScript
      # The runtime twin of `TypeScript::VOW_ERROR`: the same class, sans type
      # annotations. The `.d.ts` beside it carries the typed `code`/`hint`.
      VOW_ERROR = <<-JS
        export class VowError extends Error {
          constructor(code, message, hint = null) {
            super(message);
            this.name = "VowError";
            this.code = code;
            this.hint = hint;
          }
        }
        JS

      # The runtime twin of `TypeScript::HTTP_CLIENT` — same behaviour, no types.
      HTTP_CLIENT = <<-JS
        export function createHttpClient(url, options = {}) {
          return createClient(async (name, args, verb) => {
            const path = `${url}/${name.replaceAll(".", "/")}`;
            const res = verb === "get"
              ? await fetch(
                  Object.keys(args).length
                    ? `${path}?input=${encodeURIComponent(JSON.stringify(args))}`
                    : path,
                  { method: "GET", headers: { ...(options.headers?.() ?? {}) } },
                )
              : await fetch(path, {
                  method: "POST",
                  headers: { "Content-Type": "application/json", ...(options.headers?.() ?? {}) },
                  body: JSON.stringify(args),
                });
            const data = await res.json();
            if (!res.ok) throw new VowError(data.error, data.message, data.hint ?? null);
            return data;
          });
        }
        JS

      def self.emit(manifest : Manifest) : String
        leaf = ->(seg : String, p : ProcedureDescriptor) do
          # A zero-arg stub defaults the object so it stays callable as `fn()`.
          param = p.args.empty? ? "args = {}" : "args"
          "#{seg.camelcase(lower: true)}(#{param}) { return transport(#{p.name.inspect}, args, #{p.verb.inspect}); }"
        end
        body = Codegen.render_tree(Codegen.build_tree(manifest.procedures), 2, type_mode: false, leaf: leaf)
        String.build do |s|
          s << "// Generated by Vow — do not edit by hand.\n\n"
          s << VOW_ERROR << "\n"
          s << "\nexport function createClient(transport) {\n"
          s << "  return " << body << ";\n"
          s << "}\n"
          s << "\n" << HTTP_CLIENT << "\n"
        end
      end
    end
  end
end
